#!/usr/bin/env python3
"""Generate the graphical UI's assets as C arrays (no grit).

Writes client/source/assets.c and client/include/assets.h:
  - fonts: anti-aliased (4bpp coverage) bitmap fonts rendered from Noto Sans
  - backgrounds: 256x192 BGR555 (bit 15 = opaque) top-screen backgrounds
  - bag: the DSi Shop bag icon, BGR555 with bit 15 clear = transparent

Run from anywhere:  python3 tools/gen_assets.py
Needs Pillow and the Noto Sans fonts (SIL Open Font License).
"""
import os
from PIL import Image, ImageDraw, ImageFont

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GFX = os.path.join(ROOT, "gfx")
OUT_C = os.path.join(ROOT, "client", "source", "assets.c")
OUT_H = os.path.join(ROOT, "client", "include", "assets.h")

FONT_DIRS = ["/usr/share/fonts/noto", os.path.expanduser("~/.local/share/fonts")]
FONTS = [
    # C name,       file,                  pixel size
    ("font_small", "NotoSans-Medium.ttf", 11),
    ("font_body",  "NotoSans-Medium.ttf", 13),
    ("font_title", "NotoSans-Bold.ttf",   17),
]
FIRST_CHAR, LAST_CHAR = 32, 126

BACKGROUNDS = [
    # C name,           source image (256x192)
    ("bg_home_top",   "extracted/bg_scattered.png"),
    ("bg_detail_top", "extracted/bg_halftone.png"),
]


def find_font(name):
    for d in FONT_DIRS:
        p = os.path.join(d, name)
        if os.path.isfile(p):
            return p
    raise SystemExit(f"font {name} not found in {FONT_DIRS}")


def pixels(im):
    """All pixels, row-major (Pillow 12 deprecates getdata())."""
    return list(im.get_flattened_data() if hasattr(im, "get_flattened_data") else im.getdata())


def rgb15(r, g, b, opaque=True):
    return (0x8000 if opaque else 0) | ((b >> 3) << 10) | ((g >> 3) << 5) | (r >> 3)


def c_array(ctype, name, values, per_line=16, fmt="0x{:02x}"):
    lines = []
    for i in range(0, len(values), per_line):
        lines.append("    " + ",".join(fmt.format(v) for v in values[i:i + per_line]) + ",")
    return f"const {ctype} {name}[{len(values)}] __attribute__((aligned(4))) = {{\n" + \
        "\n".join(lines) + "\n};\n"


def gen_font(cname, fname, size):
    font = ImageFont.truetype(find_font(fname), size)
    ascent, descent = font.getmetrics()
    height = ascent + descent
    widths, offsets, bits = [], [], []
    for code in range(FIRST_CHAR, LAST_CHAR + 1):
        ch = chr(code)
        adv = max(1, round(font.getlength(ch)))
        im = Image.new("L", (adv, height), 0)
        ImageDraw.Draw(im).text((0, ascent), ch, font=font, fill=255, anchor="ls")
        px = pixels(im)
        # 4bpp coverage, slightly boosted so small text stays solid on the DS LCD
        levels = [min(15, (p * 18 + 127) // 255) for p in px]
        offsets.append(len(bits))
        for i in range(0, len(levels), 2):
            lo = levels[i]
            hi = levels[i + 1] if i + 1 < len(levels) else 0
            bits.append(lo | (hi << 4))
        widths.append(adv)
    src = c_array("u8", f"{cname}_widths", widths)
    src += c_array("u16", f"{cname}_offsets", offsets, 12, "0x{:04x}")
    src += c_array("u8", f"{cname}_bits", bits)
    src += (f"const Font {cname} = {{ {height}, {ascent}, {FIRST_CHAR}, "
            f"{LAST_CHAR - FIRST_CHAR + 1}, {cname}_widths, {cname}_offsets, {cname}_bits }};\n")
    return src, f"extern const Font {cname};\n"


def gen_background(cname, path):
    im = Image.open(os.path.join(GFX, path)).convert("RGB").resize((256, 192))
    # some panels kept a 1px teal (#008080) separator from the sprite sheet:
    # replace those pixels with their horizontal neighbour
    for y in range(192):
        for x in range(256):
            r, g, b = im.getpixel((x, y))
            if r < 40 and 100 < g < 160 and 100 < b < 160:
                im.putpixel((x, y), im.getpixel((x + 1 if x < 255 else x - 1, y)))
    vals = [rgb15(*p) for p in pixels(im)]
    return (c_array("u16", cname, vals, 12, "0x{:04x}"),
            f"extern const u16 {cname}[256 * 192];\n")


def gen_bag():
    """First (upright) bag of the HOME Menu icon sheet, without its border."""
    sheet = Image.open(os.path.join(GFX, "sheets", "bags.png")).convert("RGBA")
    cell = sheet.crop((4, 4, 30, 30))    # inside the icon's rounded border
    w, h = cell.size
    vals = []
    for (r, g, b, a) in pixels(cell):
        # the icon sits on white inside a rounded border: keep the bag, drop the rest
        is_bag = a > 128 and b > 150 and r < 150
        vals.append(rgb15(r, g, b, True) if is_bag else 0)
    return (c_array("u16", "bag_icon", vals, 12, "0x{:04x}") +
            f"const int bag_icon_w = {w}, bag_icon_h = {h};\n",
            "extern const u16 bag_icon[];\nextern const int bag_icon_w, bag_icon_h;\n")


def main():
    c = ["/* Generated by tools/gen_assets.py -- do not edit. */\n",
         '#include "assets.h"\n\n']
    h = ["/* Generated by tools/gen_assets.py -- do not edit. */\n",
         "#pragma once\n#include <nds/ndstypes.h>\n#include \"font.h\"\n\n"]
    for args in FONTS:
        cs, hs = gen_font(*args)
        c.append(cs); h.append(hs)
    for args in BACKGROUNDS:
        cs, hs = gen_background(*args)
        c.append(cs); h.append(hs)
    cs, hs = gen_bag()
    c.append(cs); h.append(hs)
    with open(OUT_C, "w") as f:
        f.write("".join(c))
    with open(OUT_H, "w") as f:
        f.write("".join(h))
    print(f"wrote {OUT_C} ({os.path.getsize(OUT_C)//1024} KB source), {OUT_H}")


if __name__ == "__main__":
    main()
