/* Generated by tools/gen_assets.py -- do not edit. */
#pragma once
#include <nds/ndstypes.h>
#include "font.h"

extern const Font font_small;
extern const Font font_body;
extern const Font font_title;
extern const u16 bg_home_top[256 * 192];
extern const u16 bg_detail_top[256 * 192];
extern const u16 bag_icon[];
extern const int bag_icon_w, bag_icon_h;
