#pragma once
#include <nds/ndstypes.h>

/* Anti-aliased bitmap font generated by tools/gen_assets.py.
   Each glyph is a cell `widths[c]` pixels wide and `height` tall, stored as
   4bpp coverage (0 = empty, 15 = solid), two pixels per byte, low nibble first. */
typedef struct {
    u8        height;     /* line height in pixels                */
    u8        ascent;     /* baseline position within the line     */
    u8        first;      /* first character code in the font      */
    u8        count;      /* number of characters                  */
    const u8  *widths;    /* advance (= cell width) per character  */
    const u16 *offsets;   /* byte offset of each glyph in `bits`   */
    const u8  *bits;
} Font;
